name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Add custom properties to local.properties
        run: |
          echo "# Cloudflare
          CF_API_KEY=\"<Cloudflare API Token>\"
          CF_EMAIL=\"<Cloudflare Email>\"
          ZONE_ID=\"<Cloudflare DNS Zone ID>\"
          RECORD_ID=\"<Cloudflare DNS Record ID>\"
          # Telegram Bot
          BOT_TOKEN=\"<Your Telegram Bot Token>\"
          CHAT_ID=\"<Your Telegram Chat ID to receives notifications>\"
          # Web server
          WEB_PORT=8443
          PC_MAC=\"<PC ethernet MAC>\"
          PC_IP=\"<PC static IP address>\"
          # If your PC is Windows, use port 3389, otherwise use port 22 for SSH
          PC_PORT=3389
          PC_TIMEOUT=1500
          CERTIFICATE_FILENAME=\"<SSL certificate in p12 format>\"" > local.properties

      - name: Build with Gradle
        run: ./gradlew assembleRelease
